### ISSUE TITLE
how to train in python load by golang?

### ISSUE THREAD

**Issue by atlantiswqq** [pa-m/sklearn#10]
as the title,i want to know,how load pkl file with golang.i train model in python with sklearn,it saved as `model.pkl`,then how i load it in golang? pls

**Comment by sbinet** [comment]
one can use this package to read pickle'd data from Go:
- http://www.hydrogen18.com/blog/reading-pickled-data-in-go.html
- https://github.com/hydrogen18/stalecucumber

but I'd advise to instead save your data in a more "structured" format: the numpy file format comes to mind.
there's also a package to read that:
- https://github.com/sbinet/npyio

hth

**Comment by atlantiswqq** [comment]
thank you,that's what i want.
