### ISSUE TITLE
Is it possible to port sklearn python pipeline into go?

### ISSUE THREAD

**Issue by rayguang** [pa-m/sklearn#11]
Thanks for this awesome project. I think a lot of existing projects using sklearn (python) are already built and tested in python environment. If there is a solution to allow data scientists to load their sklearn python models (normally they would dump to a pickle and serve in Flask) and serve in Golang, that will be very nice. Any recommendation on how to achieve this: from an existing python model -> serve in Go?

**Comment by sbinet** [comment]
does this answer your question?

https://github.com/pa-m/sklearn/issues/10#issuecomment-557599100

**Comment by sbinet** [comment]
or:

- use [Apache Arrow](https://github.com/apache/arrow)
- use [Numpy data files](https://github.com/sbinet/npyio)

**Comment by rayguang** [comment]
Thank you!

**Comment by sbinet** [comment]
feel free to point back at that issue with either what you came up with and/or with an example :)

**Comment by ozichert** [comment]
Finally you can use ONNX for that. But the current implementation is incomplete.
